services:
  - type: web
    name: glint-key-api
    runtime: python
    buildCommand: pip install fastapi gunicorn uvicorn
    startCommand: python3 -m gunicorn main:app
    envVars:
      - key: GLINT_ADMIN_KEY
        value: CHANGE_THIS_TO_YOUR_SECRET_KEY
      - key: PYTHON_VERSION
        value: 3.12.7
